services:
  - type: web
    name: expense-tracker-api
    runtime: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js

  - type: web
    name: expense-tracker
    runtime: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: frontend/dist